config/routes.rb
Rails.application.routes.draw do
  
  get 'recipes/new'
  get 'recipes/index'
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  root 'home#top'
  
  
  get 'procedures/index',         to: 'procedures#index',     as: 'procedures_index'
  get 'procedures/:id/show',      to: 'procedures#show',      as: 'procedures_show'
  get 'procedures/new',           to: 'procedures#new',       as: 'procedures_new'
  
  
  post 'procedures/create',       to: 'procedures#create',    as: 'procedure_create'
  get 'procedures/:id/edit',      to: 'procedures#edit',      as: 'procedure_edit'
  patch 'procedures/:id/update',  to: 'procedures#update',    as: 'procedure_update'
  delete 'procedures/destroy',    to: 'procedures#destroy',   as: 'procedure_destroy'
  
  get 'posts/index'
  get 'search_result',            to: 'posts#search_result',  as: 'result'
  
  get 'signup',                   to: 'users#new',            as: 'signup'
  post'user/create',              to: 'users#create',         as: 'user_create'
  get 'users/index',              to: 'users#index',          as: 'index'
  get 'users/:id',                to: 'users#show',           as: 'show'
  get 'users/:id/edit',           to: 'users#edit',           as: 'edit'
  patch 'users/:id/update',       to: 'users#update',         as: 'update'
  get 'login',                    to: 'sessions#new'
  post'login',                    to: 'sessions#create'
  delete'logout',                 to: 'sessions#destroy',     as: 'logout'
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/procedure.rb
class Procedure < ApplicationRecord
    belongs_to :recipe
    belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :procedures
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  has_many :procedures, dependent: :destroy
  attr_accessor :remember_token
  has_secure_password
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    Micropost.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #ログイン失敗時のフラッシュでbootstrapの記述
    add_flash_types :success, :info, :warning, :danger
    
    #ログインでヘッダーが変更になるヘルパーを呼び出すメソッド
    include SessionsHelper
    
    private
    
    # beforeアクション
    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @recipes = Recipe.all
  end
  
  def logged_in_top
  end
  
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  
  before_action :logged_in_user, only: [:new, :create, :destroy]
  
  def index
    @procedure = Procedure.content
  end

  def show
  end

  def new
    @procedure = Procedure.new
  end

  def create
    p "==================="
    p params[:procedure][:content]
    p "==================="
    @procedure = current_user.procedures.build(procedure_params)
    if @procedure.save
      flash.now[:success] = "レシピを作成しました"
      redirect_to procedures_index_path
    else
      flash.now[:danger] = "保存出来ませんでした"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  
  
  private
  
  def procedure_params
    params.require(:procedure).permit(:image, :content, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
  end

  def index
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    p "============================"
    p  params
    p "============================"

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = "ログインしました"
      redirect_back_or user
    else
      flash.now[:danger] = "メールまたはパスワードが間違っています"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:index,:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.birthday = "#{params[:user][:year]}/#{params[:user][:month]}/#{params[:user][:day]}"
    
    p "============================"
    p  params
    p "============================"
    if @user.save
      log_in @user
      flash[:success] = "登録完了しました"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新しました"
      redirect_to show_path
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end
  
  
  private

    def user_params
      params.require(:user).permit(:nickname, :email, :password,:password_confirmation)
    end
    
    
    
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
    # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end
  
  
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 記憶したURL（もしくはデフォルト値）にリダイレクト
  #　　　　　　　　　　　　　　　　　　　　↓このroot_pathは変更した。もともとのチュートリアルの記述ではdefaultだった　　 
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || root_path)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
    
  # 引数で与えられたユーザーのGravatar画像を返す
  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.nickname, class: "gravatar")
  end
end

app/views/home/_before_logged_in_top.html.erb
ログインや会員登録前

app/views/home/_logged_in_top.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
  <% end %>
  
  <% @recipes.each do |recipe| %>
    <%= link_to recipe.title, recipe_path(recipe.id) %><br>
  <% end %>
  表示されるはず

app/views/home/top.html.erb
<% if logged_in? %>
<%= render 'home/logged_in_top', locals: {recipes: @recipes} %>
<% else %>
<%= render 'home/before_logged_in_top' %>
<% end %>

app/views/layouts/_header.html.erb
<div class="row justify-content-center">
    <div class="col-auto d-flex align-items-center">わんにゃフル!!ディッシュ☆☆☆</div>

    <div class="col-auto">
        <div class="input-group">
            <input type="text" id="txt-search" class="form-control input-group-prepend" placeholder="キーワードを入力"></input>
            <span class="input-group-btn input-group-append">
                <submit type="submit" id="btn-search" class="btn btn-primary"><i class="fas fa-search"></i>検索</submit>
            </span>
        </div>
    </div>
    <% if logged_in? %>
        <div class="col-auto d-flex align-items-center"><%= link_to "レシピ新規作成", procedures_new_path(current_user) %></div>
        <div class="col-auto d-flex align-items-center"><a href="#">作成したレシピ一覧</a></div>
        <div class="col-auto d-flex align-items-center"><a href="#">フォロー済みユーザー一覧</a></div>
        <div class="col-auto d-flex align-items-center"><%= link_to "登録情報", edit_path(current_user) %></div>
        <div class="col-auto d-flex align-items-center"><%= link_to "ユーザー一覧", index_path(current_user) %></div>
        <div class="col-auto d-flex align-items-center"><a href="#">ヘルプ</a></div>
        <div class="col-auto d-flex align-items-center"><%= link_to "ログアウト","/logout",method: :delete %></div>
    <% else %>
        <div class="col-auto d-flex align-items-center"><a href="/signup">新規会員登録</a></div>
        <div class="col-auto d-flex align-items-center"><a href="#">初めての方へ</a></div>
        <div class="col-auto d-flex align-items-center"><a href="#">ヘルプ</a></div>
        <div class="col-auto d-flex align-items-center"><a href="/login">ログイン</a></div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pf2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
    <%#　ヘッダーの記述↓　%>
    <%= render 'layouts/header'%>
    <div container>
    <%= yield %>
    </div>
  </body>
</html>

app/views/procedures/create.html.erb
<h1>Procedures#create</h1>
<p>Find me in app/views/procedures/create.html.erb</p>

app/views/procedures/destroy.html.erb
<h1>Procedures#destroy</h1>
<p>Find me in app/views/procedures/destroy.html.erb</p>

app/views/procedures/edit.html.erb
<h1>Procedures#edit</h1>
<p>Find me in app/views/procedures/edit.html.erb</p>

app/views/procedures/index.html.erb
<h1>Procedures#index</h1>
投稿後の画面

<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
  <% end %>
  
<%= @procedure.content %>

app/views/procedures/new.html.erb
<h1>Procedures#new</h1>



<%= form_for @procedure, url: procedure_create_path do |f| %>
<%#画像アップロードの部分まだわからん%>
<%#= f.label :image %>

<%= f.label :content,"タイトル" %><br>
<%= f.text_field :content %><br>
<%= f.submit "登録する", class: "btn btn-primary"%>
<% end %>

app/views/procedures/show.html.erb
<h1>Procedures#show</h1>
<p>Find me in app/views/procedures/show.html.erb</p>

app/views/procedures/update.html.erb
<h1>Procedures#update</h1>
<p>Find me in app/views/procedures/update.html.erb</p>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<h2><%= @recipe.title %>の詳細画面</h2>

<% @recipe.procedures.each do |procedure| %>
手順<%= procedure.id %>：<%= procedure.content %><br>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1 class="row justify-content-center" id="edit_h1">登録情報</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user,url: update_path do |f| %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">画像を変更</a>
    </div>

      <%= f.label :nickname, "ニックネーム" %>
      <%= f.text_field :nickname, class: 'form-control' %>
      
      <%= f.label :gender, "性別" %>
      <%= f.text_field :gender, class: 'form-control' %>
      
      <%= f.label :birthday, "誕生日" %>
      <%= f.text_field :birthday, class: 'form-control' %>
      

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.nickname, index_path %>
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "ユーザーの削除", user, method: :delete,
                                  data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="container">
        <header>
            <h1>わんにゃフル！！ディッシュ☆☆☆<br>無料アカウント作成</h1>
        </header>
    </div>
    <hr>
    <div class="container">
        <div class=row,mx-auto>
        <%=form_for @user, url: user_create_path do |f| %>
            <div class="col-sm-4 offset-sm-4">
               
                <div class="form-group">
                    <label for="nickName">ニックネーム</label>
                    <span>あと：</span><span id="countName">0</span><span id = countMsg>文字</span>
                    <input type="text" id="nickName" oninput="countName()" name="user[nickname]" class="form-control" placeholder="例）山田太郎" required >
                </div>

                <div class="form-group">
                    <label class="d-block" for="email">メールアドレス</label>
                    <input type="mail" id="email" name="user[email]" required>
                </div>

                <div class="form-group">
                    <label  for="password">パスワード</label>
                    <span>現在：</span><span id=count>0文字</span>
                    <input type="password" id="password" oninput="pass();" name="user[password]" pattern="^(?=.*[A-Z])(/\s+/g, "")[a-zA-Z0-9.?/-]{8,24}$" required>
                </div>

                <div class="form-group">
                    <label for="password_confirmation">パスワード確認</label>
                    <input type="password" id="password_confirmation" name="user[password_confirmation]" required>
                </div>

                <div class="form-group">
                    <label class="d-block">生年月日</label>
                    <label for="year">年：</label><select id="year" name="user[year]"></select>
                    
                    <label for="month">月：</label><select id="month" name="user[month]"></select>

                    <label for="day">日：</label><select id="day" name="user[day]"></select>   
                </div>

                <div class="form-group">
                    <label class="d-block">性別</label>
                    <div class="form-check form-check-inline" >
                        <input type="radio" class="form-check-input" name="gender" id="man" value="1">
                        <label for="man" class="form-check-label">男性</label>
                    </div>

                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="gender" id="woman" value="2">
                        <label for="woman" class="form-check-label">女性</label>
                    </div>
                    
                    <div class="form-check form-check-inline">
                        <input type="radio" class="form-check-input" name="gender" id="others" value="0">
                        <label for="others" class="form-check-label">その他</label>
                    </div>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary ">入力した内容を確認する</button>
                </div>
                
                <p>アカウントを作成すると利用規約と<br>プライバシーポリシーに同意したものと<br>みなされます。</p>

                <div class="text-center">
                    <button type="button" class="btn btn-primary">すでにアカウントをお持ちの方</button>
                </div>
                
                <p>または</p>

                <p>SNSでログイン</p>
                
            </div>

        <% end %>
        </div>
    </div>

    <hr>

    <div class="container">
    <footer>
        <p>&copy; わんにゃフル！！ディッシュ☆☆☆</p>
    </footer>  
    </div> 


<script>

// 文字カウント（nickname)DOM操作



function countName(){
    const maxChar = 15;
    const nickName = document.getElementById("nickName").value;
    let countName = document.getElementById("countName");
    let countMsg = document.getElementById("countMsg");
    
    if (nickName.length > maxChar){
        countName.style.color = "red";
        let overChar = nickName.length - maxChar;
        countName.innerHTML = overChar;
        countMsg.style.color = "red";
        countMsg.innerHTML = "文字数オーバーです";
    }else{
        countName.style.color = "black";
        countName.innerHTML = nickName.length;
        countMsg.style.color= "black";
        countMsg.innerHTML = "文字";
    }
}




// 文字カウント（password)DOM操作
 function pass(){
  var len = document.getElementById("password").value.trim().length;
  document.getElementById("count").innerText = len + "文字";
}

  //誕生日欄
$(document).ready(function() {
  const monthNames = ["1月", "2月", "3月", "4月", "5月", "6月",
    "7月", "8月", "9月", "10月", "11月", "12月"
  ];
  let qntYears = 40;
  let selectYear = $("#year");
  let selectMonth = $("#month");
  let selectDay = $("#day");
  let currentYear = new Date().getFullYear();

  for (var y = 0; y < qntYears; y++) {
    let date = new Date(currentYear);
    let yearElem = document.createElement("option");
    yearElem.value = currentYear
    yearElem.textContent = currentYear;
    selectYear.append(yearElem);
    currentYear--;
  }

  for (var m = 0; m < 12; m++) {
    let month = monthNames[m];
    let monthElem = document.createElement("option");
    monthElem.value = m;
    monthElem.textContent = month;
    selectMonth.append(monthElem);
  }

  var d = new Date();
  var month = d.getMonth();
  var year = d.getFullYear();
  var day = d.getDate();

  selectYear.val(year);
  selectYear.on("change", AdjustDays);
  selectMonth.val(month);
  selectMonth.on("change", AdjustDays);

  AdjustDays();
  selectDay.val(day)

  function AdjustDays() {
    var year = selectYear.val();
    var month = parseInt(selectMonth.val()) + 1;
    selectDay.empty();

    var days = new Date(year, month, 0).getDate();

    for (var d = 1; d <= days; d++) {
      var dayElem = document.createElement("option");
      dayElem.value = d;
      dayElem.textContent = d;
      selectDay.append(dayElem);
    }
  }
});

</script>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
  <% end %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.nickname %>
</h1>

app/views/users/update.html.erb
<h1>もしやUsers#update</h1>
<p>Find me in app/views/users/update.html.erb</p>